# Generated by Django 4.1.1 on 2022-12-16 05:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField(default=7, unique=True, validators=[django.core.validators.MinValueValidator(70000000000), django.core.validators.MaxValueValidator(79999999999)], verbose_name='Номер телефона')),
                ('code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=10, verbose_name='Код оператора и тег')),
                ('timezone', models.CharField(max_length=20, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_date_time', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('message', models.TextField(verbose_name='Сообщение клиенту')),
                ('filter_code', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Фильтр кода оператора')),
                ('filter_tag', models.CharField(max_length=10, verbose_name='Фильтр тега')),
                ('finish_date_time', models.DateTimeField(verbose_name='Дата окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата/время создания/отправки сообщения')),
                ('status', models.TextField(choices=[('SENT', 'Отправлено'), ('NOT_SENT', 'Неотправлено')], default='NOT_SENT', verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing_management.client')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing_management.mailinglist')),
            ],
        ),
    ]
